language: java
jdk:
- oraclejdk8

script: mvn clean install
notifications:
  email:
    recipients:
      - leo114000@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

