language: java
jdk:
- oraclejdk8

sudo: true

dist: precise

install:
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn clean test

test:
  adapter: mysql2
  database: demo_api
  username: demo_api_admin
  password: supersecretpassword
  encoding: utf8

notifications:
  email:
    recipients:
      - leo114000@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

