language: java
jdk:
- oraclejdk8

sudo: required

services:
  - mysql

dist: trusty

install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V


script: mvn clean test

before_script:
  - mysql -u root -e 'CREATE DATABASE demo_api;'
  - mysql -u root -e 'CREATE USER 'demo_api_admin'@'localhost' IDENTIFIED BY 'supersecretpassword';'
  - mysql -u root -e 'GRANT ALL ON demo_api.* TO 'demo_api_admin'@'localhost';'

notifications:
  email:
    recipients:
      - leo114000@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

